# Generated by Django 5.1.7 on 2025-05-11 08:24

import django_mongodb_backend.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categories', models.JSONField(default=list, null=True)),
                ('city', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('seasons', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'activities_fi',
            },
        ),
        migrations.CreateModel(
            name='FiFilters',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('items', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'activities_fi_filters',
            },
        ),
    ]
