# Generated by Django 5.1.7 on 2025-04-03 10:02

import django_mongodb_backend.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('idinternal', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('accessible', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('descriptionen', models.TextField()),
                ('languages', models.CharField(max_length=255)),
                ('nameen', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('seasons', models.CharField(max_length=255)),
            ],
        ),
    ]
