# Generated by Django 5.1.7 on 2025-05-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='categories_str',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='seasons_str',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
