// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type StringOrStringArray interface {
	IsStringOrStringArray()
}

type Activity struct {
	ID         string              `json:"id"`
	Categories StringOrStringArray `json:"categories,omitempty"`
	Href       *string             `json:"href,omitempty"`
	Text       *string             `json:"text,omitempty"`
	Title      *string             `json:"title,omitempty"`
}

type Query struct {
}

type SingleString struct {
	Value *string `json:"value,omitempty"`
}

func (SingleString) IsStringOrStringArray() {}

type StringArray struct {
	Value []string `json:"value,omitempty"`
}

func (StringArray) IsStringOrStringArray() {}
