package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"backend/graphql/graph/model"
	"context"
)

// Activityid is the resolver for the activityid field.
func (r *queryResolver) Activityid(ctx context.Context, id string) (*model.Activity, error) {
	dummyActivity := model.Activity{
		// ID:         "testId",
		// Categories: [3]string{"A", "B", "C"},
		// Href:       "https://www.google.com/",
		// Text:       "this is am amazing place",
		// Title:      "test title",
	}
	return &dummyActivity, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
