package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"backend/graphql/graph/model"
	"context"
)

// TODO: remove dummyActivity, get real data from mongoDB
// Activities is the resolver for the activities field.
func (r *queryResolver) Activities(ctx context.Context, count *int) ([]*model.Activity, error) {
	var activities []*model.Activity
	categories := model.StringArray{Value: []string{"A", "B", "C"}}
	href := "https://www.google.com/"
	text := "this is am amazing place"
	title := "test title"
	dummyActivity := model.Activity{
		ID:         "testId",
		Categories: categories,
		Href:       &href,
		Text:       &text,
		Title:      &title,
	}
	activities = append(activities, &dummyActivity)
	return activities, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
